from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer,
    PageBreak, Table, TableStyle
)
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import A4
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase import pdfmetrics
from reportlab.platypus import HRFlowable


# -------------------------------
# Footer with Page Numbers
# -------------------------------

def add_footer(canvas, doc):
    canvas.saveState()
    width, height = A4

    canvas.setFont("Helvetica", 9)
    canvas.setFillColor(colors.grey)

    canvas.drawString(
        inch,
        0.5 * inch,
        "Generated by TripMind AI – Smart Travel Planning"
    )

    canvas.drawRightString(
        width - inch,
        0.5 * inch,
        f"Page {doc.page}"
    )

    canvas.restoreState()


# -------------------------------
# Main PDF Creator
# -------------------------------

def create_pdf(itinerary_text, total_budget, per_day_budget,
               filename="premium_itinerary.pdf"):

    doc = SimpleDocTemplate(
        filename,
        pagesize=A4,
        rightMargin=40,
        leftMargin=40,
        topMargin=50,
        bottomMargin=70
    )

    elements = []
    styles = getSampleStyleSheet()

    # -------------------------------
    # Custom Styles
    # -------------------------------

    title_style = ParagraphStyle(
        "TitleStyle",
        parent=styles["Heading1"],
        fontSize=26,
        textColor=colors.HexColor("#1F3C88"),
        spaceAfter=20,
    )

    subtitle_style = ParagraphStyle(
        "SubTitleStyle",
        parent=styles["Normal"],
        fontSize=14,
        textColor=colors.grey,
        spaceAfter=30,
    )

    section_style = ParagraphStyle(
        "SectionStyle",
        parent=styles["Heading2"],
        fontSize=18,
        textColor=colors.HexColor("#0F3057"),
        spaceAfter=12,
    )

    normal_style = ParagraphStyle(
        "NormalStyle",
        parent=styles["Normal"],
        fontSize=11,
        leading=16,
    )

    # -------------------------------
    # COVER PAGE
    # -------------------------------

    elements.append(Paragraph("TripMind AI", title_style))
    elements.append(Paragraph("Premium Personalized Travel Itinerary", subtitle_style))
    elements.append(Spacer(1, 1 * inch))

    elements.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor("#1F3C88")))
    elements.append(Spacer(1, 0.5 * inch))

    elements.append(Paragraph(
        "Crafted with intelligent planning, optimized routes, and budget-aware recommendations.",
        normal_style
    ))

    elements.append(PageBreak())

    # -------------------------------
    # BUDGET SUMMARY BOX
    # -------------------------------

    elements.append(Paragraph("Budget Summary", section_style))
    elements.append(Spacer(1, 0.2 * inch))

    budget_data = [
        ["Estimated Per Day", f"₹{per_day_budget}"],
        ["Total Estimated Budget", f"₹{total_budget}"]
    ]

    budget_table = Table(budget_data, colWidths=[3 * inch, 2 * inch])

    budget_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#EAF1FB")),
        ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -1), 12),
        ('INNERGRID', (0, 0), (-1, -1), 0.25, colors.grey),
        ('BOX', (0, 0), (-1, -1), 0.5, colors.grey),
        ('ALIGN', (1, 0), (-1, -1), 'RIGHT')
    ]))

    elements.append(budget_table)
    elements.append(Spacer(1, 0.6 * inch))

    # -------------------------------
    # ITINERARY CONTENT
    # -------------------------------

    lines = itinerary_text.split("\n")

    for line in lines:

        if "DAY" in line or "TRIP OVERVIEW" in line:
            elements.append(Spacer(1, 0.4 * inch))
            elements.append(Paragraph(line, section_style))
            elements.append(Spacer(1, 0.2 * inch))
        else:
            elements.append(Paragraph(line, normal_style))
            elements.append(Spacer(1, 0.15 * inch))

    elements.append(PageBreak())

    # -------------------------------
    # PRO TIPS SECTION
    # -------------------------------

    elements.append(Paragraph("Pro Travel Tips", section_style))
    elements.append(Spacer(1, 0.3 * inch))

    tips = [
        "• Always keep local emergency contacts saved offline.",
        "• Download offline Google Maps for navigation.",
        "• Start early to avoid tourist rush.",
        "• Carry small cash for local vendors.",
        "• Confirm transport availability during peak seasons."
    ]

    for tip in tips:
        elements.append(Paragraph(tip, normal_style))
        elements.append(Spacer(1, 0.2 * inch))

    # -------------------------------
    # Build PDF
    # -------------------------------

    doc.build(elements, onFirstPage=add_footer, onLaterPages=add_footer)

    return filename